import { EventBus } from './core/event-bus.js';
import { StateStore } from './core/state-store.js';
import { createState } from './core/state.js';
import { createRuntime } from './core/runtime.js';
import { createDomainAuthority } from './core/domain-authority.js';
import { GameLoop } from './core/game-loop.js';
import { SystemRegistry } from './systems/registry.js';
import { createSystems } from './systems/index.js';
import { legacyBridge } from './core/legacy-bridge.js';
import { createMigrationBridge } from './core/migration-bridge.js';
import { SaveManager } from './save/save-manager.js';
import { createUIStateBridge } from './ui/state-bridge.js';
import { createCommandBus } from './core/commands.js';
import { registerCommandAdapters } from './core/command-registry.js';
import { bindGameplayCommands } from './ui/actions.js';
import { createGameAgent } from './agent/game-agent.js';
import { createDecisionEngine } from './agent/decision-engine.js';
import { createAutopilot } from './agent/autopilot.js';
import { createAgentPanel } from './ui/agent-panel.js';
import { createPlayerGuide } from './ui/player-guide.js';

const bus=new EventBus();
const state=new StateStore(createState({meta:{runtimeVersion:'20.23.0'}}));
const runtime=createRuntime({bus,state});
const authority=createDomainAuthority(state);
const registry=new SystemRegistry(runtime);
const loop=new GameLoop();
const migration=createMigrationBridge(window);
const commands=createCommandBus(runtime);

runtime.register('bridge',legacyBridge());
runtime.register('migration',migration);
runtime.register('authority',authority);
for(const [name,system] of Object.entries(createSystems(migration,authority))) runtime.register(name,system);
registerCommandAdapters(commands,migration,runtime,authority);
runtime.register('commands',commands);
runtime.register('save',SaveManager);
runtime.register('registry',registry);
const agent=createGameAgent(runtime);
const decisionEngine=createDecisionEngine(agent);
runtime.register('agent',agent);
runtime.register('decisionEngine',decisionEngine);
const autopilot=createAutopilot(agent,decisionEngine);
runtime.register('autopilot',autopilot);
loop.add(registry);
runtime.register('loop',loop);

for(const name of ['resources','villagerMigration','productionMigration','buildingMigration','combatMigration','worldMigration']) runtime.get(name)?.refresh?.('bootstrap');
authority.commit('save',{key:SaveManager.key,version:SaveManager.version},{source:'v20-core'});

const uiActions=bindGameplayCommands(commands);
authority.commit('ui',{commandBindings:Object.keys(uiActions).filter(key=>uiActions[key]),stateBridge:'one-way',adaptiveHud:true,strategicAgent:'20.22',playerGuidance:'stage6-early-quest-coach'},{source:'v20-core'});

const api={runtime,bus,state,loop,migration,authority,save:SaveManager,commands,agent,decisionEngine,autopilot,uiActions,uiBridge:null,agentPanel:null,playerGuide:null};
api.uiBridge=createUIStateBridge(runtime);
api.agentPanel=createAgentPanel(agent,decisionEngine,autopilot);
api.playerGuide=createPlayerGuide(document);
api.playerGuide.start();
if(document.readyState!=='complete') window.addEventListener('load',()=>api.playerGuide.start(),{once:true});
window.MyCampGame=Object.freeze(api);
document.documentElement.dataset.v20Foundation='1';
document.documentElement.dataset.v20Migration='domain-authority';
document.documentElement.dataset.v20Authority='domain-v1';
document.documentElement.dataset.v20Resources='authority-v20';
document.documentElement.dataset.v20Villagers='authority-v20';
document.documentElement.dataset.v20Production='authority-v20';
document.documentElement.dataset.v20Buildings='authority-v20';
document.documentElement.dataset.v20Combat='authority-v20';
document.documentElement.dataset.v20World='authority-v20';
document.documentElement.dataset.v20Save='authority-versioned';
document.documentElement.dataset.v20Commands='strategic-wired';
document.documentElement.dataset.v20Agent='20.22';
document.documentElement.dataset.v20DecisionEngine='strategic-planner';
document.documentElement.dataset.v20Autopilot='action-aware-disabled-by-default';
document.documentElement.dataset.v20AgentPanel='strategic';
document.documentElement.dataset.v20PlayerGuide='stage6-quest-coach-v1';
document.documentElement.dataset.v20Stabilization='20.20';
window.dispatchEvent(new CustomEvent('mycamp:v20-ready',{detail:runtime}));
if(document.readyState==='complete') loop.start();else window.addEventListener('load',()=>loop.start(),{once:true});
