import { EventBus } from './core/event-bus.js';
import { StateStore } from './core/state-store.js';
import { createState } from './core/state.js';
import { createRuntime } from './core/runtime.js';
import { GameLoop } from './core/game-loop.js';
import { SystemRegistry } from './systems/registry.js';
import { createSystems } from './systems/index.js';
import { legacyBridge } from './core/legacy-bridge.js';
import { createMigrationBridge } from './core/migration-bridge.js';
import { SaveManager } from './save/save-manager.js';
import { createUIStateBridge } from './ui/state-bridge.js';
import { createCommandBus } from './core/commands.js';
import { registerCommandAdapters } from './core/command-registry.js';
import { bindGameplayCommands } from './ui/actions.js';

const bus = new EventBus();
const state = new StateStore(createState({ meta: { runtimeVersion: '20.12.0' } }));
const runtime = createRuntime({ bus, state });
const registry = new SystemRegistry(runtime);
const loop = new GameLoop();
const migration = createMigrationBridge(window);
const commands = createCommandBus(runtime);

runtime.register('bridge', legacyBridge());
runtime.register('migration', migration);
for (const [name, system] of Object.entries(createSystems(migration))) runtime.register(name, system);
registerCommandAdapters(commands, migration);
runtime.register('commands', commands);
runtime.register('save', SaveManager);
runtime.register('registry', registry);
loop.add(registry);
runtime.register('loop', loop);

const uiActions = bindGameplayCommands(commands);
const api = { runtime, bus, state, loop, migration, save: SaveManager, commands, uiActions, uiBridge: null };
window.MyCampGame = Object.freeze(api);
api.uiBridge = createUIStateBridge(runtime);
document.documentElement.dataset.v20Foundation = '1';
document.documentElement.dataset.v20Migration = 'controlled';
document.documentElement.dataset.v20Resources = 'migrated-readonly';
document.documentElement.dataset.v20Villagers = 'migrated-readonly';
document.documentElement.dataset.v20Production = 'migrated-readonly';
document.documentElement.dataset.v20Buildings = 'migrated-readonly';
document.documentElement.dataset.v20Combat = 'migrated-readonly';
document.documentElement.dataset.v20World = 'migrated-readonly';
document.documentElement.dataset.v20Save = 'versioned';
document.documentElement.dataset.v20Commands = 'wired';
window.dispatchEvent(new CustomEvent('mycamp:v20-ready', { detail: runtime }));

if (document.readyState === 'complete') loop.start();
else window.addEventListener('load', () => loop.start(), { once: true });
